import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { DetailShell } from "../../components/Sections";
import { analyses } from "../../data";
export function generateStaticParams() { return analyses.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const work = analyses.find((item) => item.slug === slug); return work ? { title: work.title, description: work.summary } : {}; }
export default async function AnalysisDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const work = analyses.find((item) => item.slug === slug); if (!work) notFound();
  if (slug === "how-romantic-scene-works") return <DetailShell work={work}><h2 id="background">1. 分析对象</h2><p>女性向剧情游戏中的关系升温片段，分析范围为“日常任务结束后的一段双人剧情”。本文关注通用设计方法，案例已匿名化，不涉及商业项目内部资料。</p><h2>2. 核心结论</h2><blockquote>有效的心动并不依赖突然表白，而依赖玩家先预测一个“安全答案”，剧情再用比预期多半步的私人回应打破它。心动来自可理解的意外：角色没有违背人设，却让玩家第一次看见只对自己开放的例外。</blockquote><h2 id="main-content">3. 设计拆解</h2><h3>期待：先建立角色的行为基线</h3><p>前置剧情反复强调角色不喜欢肢体接触、习惯保持边界。玩家因此会主动降低期待。这个基线不是阻碍，而是后续“例外”产生价值的必要条件。</p><h3>动作：比台词早半秒暴露真心</h3><p>角色先下意识握住女主手腕，确认安全后才松开，并用任务理由解释。动作先于理性，给玩家一个短暂窗口看见他的真实优先级；解释则把人物拉回一贯的克制。</p><h3>台词：答案只比预期多半步</h3><table><thead><tr><th>层次</th><th>表层台词</th><th>玩家接收的潜台词</th></tr></thead><tbody><tr><td>安全答案</td><td>“这是任务需要。”</td><td>行为没有私人意义</td></tr><tr><td>例外信息</td><td>“但换成别人，我不会这样做。”</td><td>你拥有特别权限</td></tr><tr><td>关系确认</td><td>“所以，别急着松开。”</td><td>我也希望这一刻继续</td></tr></tbody></table><h3>情绪曲线</h3><p>日常稳定 → 微小危险 → 本能保护 → 理性解释造成失落 → 例外信息反转 → 角色主动延长接触。反转前必须保留短暂失落，心动峰值才有落差。</p><h2>4. 有效之处</h2><p>它没有让角色突然变得直白，而是用“例外”证明关系变化。玩家获得的不是通用浪漫桥段，而是对人物防线的具体突破，因此更容易形成专属感。</p><h2>5. 问题与优化</h2><p>若前置章节没有充分建立边界感，这段台词会显得刻意。优化时应在更早的公共场景加入一次他对他人保持距离的对照；成本较低，只需补充动作与两句对白，却能显著增强回收感。</p><h2 id="review">6. 我的收获</h2><p>写关系推进时，不能只问“这句是否浪漫”，还要问“它突破了人物的哪条旧规则”。先把规则写清楚，例外才会被玩家感知为关系成长，而不是作者强行发糖。</p></DetailShell>;
  return <DetailShell work={work}><h2 id="background">1. 分析对象</h2><p>七日轻互动版本活动：玩家每天完成约三分钟操作，解锁一段角色反馈与一份收集物。本文从回访动机与陪伴感建立拆解其有效结构。</p><h2>2. 核心结论</h2><blockquote>轻玩法的价值不是“足够好玩”，而是给角色回应提供可信的触发理由。操作必须短、结果必须私密、次日期待必须明确；否则重复动作会先于情感积累成为负担。</blockquote><h2 id="main-content">3. 玩家路径</h2><p>进入活动 → 看见今日委托 → 完成一次选择 → 收到角色即时回应 → 获得收集物 → 预告明日关系变化。</p><h3>为什么愿意回来</h3><ul><li>今天的选择会改变一句私人留言，形成“他记得我做过什么”的感受；</li><li>七份收集物最终拼成完整事件，提供清晰终点；</li><li>次日预告不泄露剧情，只抛出一个关系问题。</li></ul><h3>可能流失的位置</h3><ul><li>第三天开始重复同一操作，若反馈只是换皮文本，玩家会识别为劳动；</li><li>关键剧情全部压在第七天，前六天的情绪回报不足；</li><li>奖励入口过深，玩家无法快速确认今日是否完成。</li></ul><h2>4. 优化方案</h2><table><thead><tr><th>问题</th><th>调整</th><th>预计影响</th><th>成本</th></tr></thead><tbody><tr><td>操作重复</td><td>第 4 天切换为双选对话</td><td>制造中段新鲜感</td><td>低</td></tr><tr><td>情绪回报晚</td><td>第 3/5 天加入小峰值</td><td>降低中途流失</td><td>中</td></tr><tr><td>完成感不清</td><td>首页展示七日来信进度</td><td>目标更明确</td><td>低</td></tr></tbody></table><h2 id="review">5. 我的收获</h2><p>陪伴感来自连续、具体、带记忆的回应，而不是上线次数本身。设计活动时应把“每天多知道角色的一件事”作为内容验收标准，再决定操作量与奖励。</p></DetailShell>;
}
