import fs from "node:fs";
import { createCanvas } from "@napi-rs/canvas";
const canvas = createCanvas(128, 128);
const context = canvas.getContext("2d");
context.fillStyle = "#F8F5EE";
context.fillRect(0, 0, 128, 128);
context.fillStyle = "#B9C8A4";
context.beginPath();
context.arc(64, 64, 48, 0, Math.PI * 2);
context.fill();
context.strokeStyle = "#171717";
context.lineWidth = 3;
context.stroke();
context.fillStyle = "#171717";
context.font = "bold 38px Georgia";
context.textAlign = "center";
context.textBaseline = "middle";
context.fillText("ZM", 64, 66);
fs.writeFileSync(new URL("../public/favicon.png", import.meta.url), canvas.toBuffer("image/png"));
